package com.example.hospital.mybatis.model;

import java.util.ArrayList;
import java.util.List;

public class AssignedPatientsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public AssignedPatientsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPatientsIdIsNull() {
            addCriterion("PATIENTS_ID is null");
            return (Criteria) this;
        }

        public Criteria andPatientsIdIsNotNull() {
            addCriterion("PATIENTS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPatientsIdEqualTo(Long value) {
            addCriterion("PATIENTS_ID =", value, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdNotEqualTo(Long value) {
            addCriterion("PATIENTS_ID <>", value, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdGreaterThan(Long value) {
            addCriterion("PATIENTS_ID >", value, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PATIENTS_ID >=", value, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdLessThan(Long value) {
            addCriterion("PATIENTS_ID <", value, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdLessThanOrEqualTo(Long value) {
            addCriterion("PATIENTS_ID <=", value, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdIn(List<Long> values) {
            addCriterion("PATIENTS_ID in", values, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdNotIn(List<Long> values) {
            addCriterion("PATIENTS_ID not in", values, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdBetween(Long value1, Long value2) {
            addCriterion("PATIENTS_ID between", value1, value2, "patientsId");
            return (Criteria) this;
        }

        public Criteria andPatientsIdNotBetween(Long value1, Long value2) {
            addCriterion("PATIENTS_ID not between", value1, value2, "patientsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdIsNull() {
            addCriterion("SPECIALISTS_ID is null");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdIsNotNull() {
            addCriterion("SPECIALISTS_ID is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdEqualTo(Long value) {
            addCriterion("SPECIALISTS_ID =", value, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdNotEqualTo(Long value) {
            addCriterion("SPECIALISTS_ID <>", value, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdGreaterThan(Long value) {
            addCriterion("SPECIALISTS_ID >", value, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdGreaterThanOrEqualTo(Long value) {
            addCriterion("SPECIALISTS_ID >=", value, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdLessThan(Long value) {
            addCriterion("SPECIALISTS_ID <", value, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdLessThanOrEqualTo(Long value) {
            addCriterion("SPECIALISTS_ID <=", value, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdIn(List<Long> values) {
            addCriterion("SPECIALISTS_ID in", values, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdNotIn(List<Long> values) {
            addCriterion("SPECIALISTS_ID not in", values, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdBetween(Long value1, Long value2) {
            addCriterion("SPECIALISTS_ID between", value1, value2, "specialistsId");
            return (Criteria) this;
        }

        public Criteria andSpecialistsIdNotBetween(Long value1, Long value2) {
            addCriterion("SPECIALISTS_ID not between", value1, value2, "specialistsId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated do_not_delete_during_merge Mon May 08 03:01:08 EEST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}