package com.example.hospital.mybatis.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.ID
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.FLOOR
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    private Integer floor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEPARTMENT.NAME
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.ID
     *
     * @return the value of DEPARTMENT.ID
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.ID
     *
     * @param id the value for DEPARTMENT.ID
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.FLOOR
     *
     * @return the value of DEPARTMENT.FLOOR
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    public Integer getFloor() {
        return floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.FLOOR
     *
     * @param floor the value for DEPARTMENT.FLOOR
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    public void setFloor(Integer floor) {
        this.floor = floor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEPARTMENT.NAME
     *
     * @return the value of DEPARTMENT.NAME
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEPARTMENT.NAME
     *
     * @param name the value for DEPARTMENT.NAME
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}