package com.example.hospital.mybatis.model;

public class Patient {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.ID
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.COUNTRYCODE
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    private String countrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.FULLNAME
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PATIENT.NATIONALID
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    private String nationalid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.ID
     *
     * @return the value of PATIENT.ID
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.ID
     *
     * @param id the value for PATIENT.ID
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.COUNTRYCODE
     *
     * @return the value of PATIENT.COUNTRYCODE
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.COUNTRYCODE
     *
     * @param countrycode the value for PATIENT.COUNTRYCODE
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.FULLNAME
     *
     * @return the value of PATIENT.FULLNAME
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.FULLNAME
     *
     * @param fullname the value for PATIENT.FULLNAME
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PATIENT.NATIONALID
     *
     * @return the value of PATIENT.NATIONALID
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public String getNationalid() {
        return nationalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PATIENT.NATIONALID
     *
     * @param nationalid the value for PATIENT.NATIONALID
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    public void setNationalid(String nationalid) {
        this.nationalid = nationalid == null ? null : nationalid.trim();
    }
}