package com.example.hospital.mybatis.model;

public class Specialist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIST.ID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIST.COUNTRYCODE
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    private String countrycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIST.FULLNAME
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIST.NATIONALID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    private String nationalid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIST.SPECIALTY
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    private Short specialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SPECIALIST.DEPARTMENTID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    private Integer departmentid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIST.ID
     *
     * @return the value of SPECIALIST.ID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIST.ID
     *
     * @param id the value for SPECIALIST.ID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIST.COUNTRYCODE
     *
     * @return the value of SPECIALIST.COUNTRYCODE
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIST.COUNTRYCODE
     *
     * @param countrycode the value for SPECIALIST.COUNTRYCODE
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIST.FULLNAME
     *
     * @return the value of SPECIALIST.FULLNAME
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIST.FULLNAME
     *
     * @param fullname the value for SPECIALIST.FULLNAME
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIST.NATIONALID
     *
     * @return the value of SPECIALIST.NATIONALID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public String getNationalid() {
        return nationalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIST.NATIONALID
     *
     * @param nationalid the value for SPECIALIST.NATIONALID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setNationalid(String nationalid) {
        this.nationalid = nationalid == null ? null : nationalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIST.SPECIALTY
     *
     * @return the value of SPECIALIST.SPECIALTY
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public Short getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIST.SPECIALTY
     *
     * @param specialty the value for SPECIALIST.SPECIALTY
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setSpecialty(Short specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SPECIALIST.DEPARTMENTID
     *
     * @return the value of SPECIALIST.DEPARTMENTID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public Integer getDepartmentid() {
        return departmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SPECIALIST.DEPARTMENTID
     *
     * @param departmentid the value for SPECIALIST.DEPARTMENTID
     *
     * @mbg.generated Mon May 08 03:01:08 EEST 2023
     */
    public void setDepartmentid(Integer departmentid) {
        this.departmentid = departmentid;
    }
}