package com.example.hospital.mybatis.dao;

import com.example.hospital.mybatis.model.AssignedPatients;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface AssignedPatientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int insert(AssignedPatients row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    List<AssignedPatients> selectAll();
}