package com.example.hospital.mybatis.dao;

import com.example.hospital.mybatis.model.AssignedPatients;
import com.example.hospital.mybatis.model.AssignedPatientsExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface AssignedPatientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    long countByExample(AssignedPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    int deleteByExample(AssignedPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    int insert(AssignedPatients row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    int insertSelective(AssignedPatients row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    List<AssignedPatients> selectByExample(AssignedPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    int updateByExampleSelective(@Param("row") AssignedPatients row, @Param("example") AssignedPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ASSIGNEDPATIENTS
     *
     * @mbg.generated Mon May 08 06:13:04 EEST 2023
     */
    int updateByExample(@Param("row") AssignedPatients row, @Param("example") AssignedPatientsExample example);
}