package com.example.hospital.mybatis.dao;

import com.example.hospital.mybatis.model.Department;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface DepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int insert(Department row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    Department selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    List<Department> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEPARTMENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int updateByPrimaryKey(Department row);
}