package com.example.hospital.mybatis.dao;

import com.example.hospital.mybatis.model.Patient;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int insert(Patient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    Patient selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    List<Patient> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int updateByPrimaryKey(Patient row);
}