package com.example.hospital.mybatis.dao;

import com.example.hospital.mybatis.model.Patient;
import com.example.hospital.mybatis.model.PatientExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PatientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    long countByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int deleteByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int insert(Patient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int insertSelective(Patient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    List<Patient> selectByExample(PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    Patient selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int updateByExampleSelective(@Param("row") Patient row, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int updateByExample(@Param("row") Patient row, @Param("example") PatientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int updateByPrimaryKeySelective(Patient row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PATIENT
     *
     * @mbg.generated Mon May 08 00:48:13 EEST 2023
     */
    int updateByPrimaryKey(Patient row);
}