package com.example.hospital.mybatis.dao;

import com.example.hospital.mybatis.model.Specialist;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface SpecialistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIST
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIST
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int insert(Specialist row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIST
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    Specialist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIST
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    List<Specialist> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SPECIALIST
     *
     * @mbg.generated Mon May 08 18:01:13 EEST 2023
     */
    int updateByPrimaryKey(Specialist row);
}